# Generated by Django 6.0.4 on 2026-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_documents/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='eligible_for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='number_plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='number_plates/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
