# Generated by Django 6.0.4 on 2026-04-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tollpasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollpass',
            name='renewal_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
