# Generated by Django 6.0.4 on 2026-04-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('unavailable', 'Unavailable')], default='unavailable', max_length=20)),
                ('status_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TollRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_rates', to='bridges.bridge')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_rates', to='vehicles.vehicletype')),
            ],
            options={
                'unique_together': {('bridge', 'vehicle_type')},
            },
        ),
    ]
