# Generated by Django 6.0.4 on 2026-04-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridge',
            name='toll_amount',
        ),
        migrations.CreateModel(
            name='TollRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('bike', 'Bike')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_rates', to='bridges.bridge')),
            ],
            options={
                'unique_together': {('bridge', 'vehicle_type')},
            },
        ),
    ]
