# Generated by Django 6.0.4 on 2026-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollrate',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
