# Generated by Django 6.0.4 on 2026-04-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0002_tollrate_disabled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='bridges.district')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='bridges.district')),
            ],
            options={
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='RouteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('estimated_time', models.CharField(max_length=50)),
                ('icon', models.CharField(default='flash', max_length=50)),
                ('color', models.CharField(default='#8b5cf6', max_length=20)),
                ('bridges', models.ManyToManyField(blank=True, related_name='route_options', to='bridges.bridge')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bridges.route')),
            ],
        ),
    ]
