# Generated by Django 6.0.4 on 2026-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nid_image',
            field=models.ImageField(blank=True, null=True, upload_to='nid_cards/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
